# Generated by Django 5.1.1 on 2024-09-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=20)),
                ('departure_time', models.CharField(max_length=30)),
                ('stops', models.CharField(max_length=10)),
                ('arrival_time', models.CharField(max_length=6)),
                ('passenger_class', models.CharField(max_length=10)),
                ('duration', models.FloatField()),
                ('days_left', models.IntegerField()),
                ('price', models.FloatField(max_length=6)),
            ],
        ),
    ]
