# Generated by Django 5.1.1 on 2024-09-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plane', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='recommend',
            field=models.BooleanField(default=False),
        ),
    ]
